const products = [
  {
    id: 1,
    category: "Men",
    type: "jacket",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L"],
    image: "/images/amir-esrafili-mzBfIKuNBxI-unsplash.jpg",

    stock: 1,
    rating: 4.5,
    numReviews: 12,
    bestSeller: true,
  },
  {
    id: 2,
    category: "Women",
    type: "blazer",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L", "XL"],
    image: "/images/laura-chouette-Pv3DjB4Q7nk-unsplash.jpg",

    stock: 3,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 3,
    category: "Men",
    type: "t-shirt",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L"],
    image: "/images/pexels-вальдемар-7643904.jpg",

    stock: 21,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 4,
    category: "Women",
    type: "t-shirt",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L"],
    image: "/images/pexels-dziana-hasanbekava-7626613.jpg",

    stock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  //{
  //   id: 1,
  //   category: "Men",
  //   type: "t-shirt",
  //   price: 250,
  //   colors: ["red", "grey"],
  //   size: ["S", "M", "L"],
  //   images: [
  //     "/images/portrait-happy-handsome-young-man-posing-isolated-background.jpg",
  //     "/images/portrait-happy-handsome-young-man-posing-isolated-background.jpg",
  //     "/images/portrait-happy-handsome-young-man-posing-isolated-background.jpg",
  //     "/images/portrait-happy-handsome-young-man-posing-isolated-background.jpg",
  //   ],
  //   stock: 1,
  //   rating: 4.5,
  //   numReviews: 12,
  // },
  // {
  //   id: 1,
  //   category: "Women",
  //   type: "shirt",
  //   price: 250,
  //   colors: ["red", "grey"],
  //   size: ["S", "M", "L"],
  //   images: [
  //     "/images/pexels-карина-каржавина-7945542.jpg",
  //     "/images/pexels-карина-каржавина-7945542.jpg",
  //     "/images/pexels-карина-каржавина-7945542.jpg",
  //     "/images/pexels-карина-каржавина-7945542.jpg",
  //   ],
  //   stock: 1,
  //   rating: 4.5,
  //   numReviews: 12,
  // },
];

const featuredProducts = [
  {
    id: 1,
    category: "Men",
    type: "jacket",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L"],
    image: "/images/amir-esrafili-mzBfIKuNBxI-unsplash.jpg",

    stock: 1,
    rating: 4.5,
    numReviews: 12,
    bestSeller: true,
    sale: 5,
  },
  {
    id: 2,
    category: "Women",
    type: "blazer",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L", "XL"],
    image: "/images/laura-chouette-Pv3DjB4Q7nk-unsplash.jpg",

    stock: 3,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 3,
    category: "Men",
    type: "t-shirt",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L"],
    image: "/images/pexels-вальдемар-7643904.jpg",

    stock: 21,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 4,
    category: "Women",
    type: "t-shirt",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L"],
    image: "/images/pexels-dziana-hasanbekava-7626613.jpg",

    stock: 1,
    rating: 4.5,
    numReviews: 12,
    sale: 15,
  },
  {
    id: 1,
    category: "Men",
    type: "t-shirt",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L"],
    image:
      "/images/portrait-happy-handsome-young-man-posing-isolated-background.jpg",

    stock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 1,
    category: "Women",
    type: "shirt",
    price: 250,
    colors: ["red", "grey"],
    size: ["S", "M", "L"],
    image: "/images/pexels-карина-каржавина-7945542.jpg",

    stock: 1,
    rating: 4.5,
    numReviews: 12,
    sale: 25,
  },
];

export { products, featuredProducts };
